const SEATS = ['west', 'north', 'east', 'south'];
const SUIT_LETTERS = ['S', 'H', 'D', 'C'];
const STRAIN_LABELS = { N: 'NT', S: '<span class="black">&spades;</span>',
  H: '<span class="red">&hearts;</span>', D: '<span class="red">&diams;</span>',
  C: '<span class="black">&clubs;</span>' };
const VALID_CHARS = /^[AaKkQqJjTt1098765432Xx\- ]*$/;
const VALID_RANKS = new Set(['2','3','4','5','6','7','8','9','T','J','Q','K','A','X']);

const RANKS = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];
// Deal collections to offer, backed by DEALS (see deals.js, generated by
// gen_deals.py from hard_deals/ and freak_deals/).
const DEAL_DIRS = [
  { id: 'freakDealNum', dir: 'freak_deals', label: 'Freak deal' },
  { id: 'hardDealNum', dir: 'hard_deals', label: 'Hard deal' },
];

const dealBtn = document.getElementById('deal');
const solveBtn = document.getElementById('solve');
const statusEl = document.getElementById('status');
const tableEl = document.getElementById('table');

for (const { id, dir, label } of DEAL_DIRS) {
  const select = document.getElementById(id);
  const nums = Object.keys(DEALS[dir]).map(Number).sort((a, b) => a - b);
  for (const n of nums) {
    const option = document.createElement('option');
    option.value = n;
    option.textContent = `${label} ${n}`;
    select.appendChild(option);
  }
}

const worker = new Worker('worker.js');

worker.onmessage = (event) => {
  const [type, ...rest] = event.data;
  switch (type) {
    case 'ready':
      solveBtn.disabled = false;
      statusEl.textContent = 'Ready.';
      break;
    case 'abort':
      statusEl.textContent = 'Solver crashed: ' + rest[0];
      solveBtn.disabled = false;
      break;
    case 'solve': {
      const [result, elapsedMs] = rest;
      renderTable(result);
      statusEl.textContent = `Solved in ${elapsedMs.toFixed(0)} ms.`;
      solveBtn.disabled = false;
      break;
    }
  }
};

// Splits a hand's suit token (e.g. "KJ1042" or "X") into individual rank
// characters, treating "10" as a single "T" rank.
function parseRanks(token) {
  const ranks = [];
  for (let i = 0; i < token.length; ++i) {
    if (token[i] === '1' && token[i + 1] === '0') {
      ranks.push('T');
      ++i;
    } else {
      ranks.push(token[i].toUpperCase());
    }
  }
  return ranks;
}

// Basic client-side validation so obviously bad input (typos, duplicate
// cards, wrong-size hands) is caught before it reaches solve(). The wasm
// side aborts on bad characters or a duplicate card, but silently accepts
// hands of unequal size -- Hands::num_tricks() just reads West's card
// count, with no cross-check against the other three seats -- so a short
// hand doesn't error, it just solves something other than the deal you
// typed.
function validateHands(hands) {
  const seen = new Set();
  for (const seat of SEATS) {
    const Seat = seat[0].toUpperCase() + seat.slice(1);
    const value = hands[seat];
    if (!VALID_CHARS.test(value)) {
      return `${Seat}: only card ranks (2-9,T,J,Q,K,A,X), '-' and spaces are allowed.`;
    }
    const suits = value.trim().length ? value.trim().split(/\s+/) : [];
    let cardCount = 0;
    for (let i = 0; i < suits.length && i < 4; ++i) {
      const token = suits[i];
      if (token === '-') continue;
      for (const rank of parseRanks(token)) {
        if (!VALID_RANKS.has(rank)) return `${Seat}: invalid rank '${rank}'.`;
        ++cardCount;
        if (rank === 'X') continue;
        const card = SUIT_LETTERS[i] + rank;
        if (seen.has(card)) return `Duplicate card: ${card}`;
        seen.add(card);
      }
    }
    if (cardCount !== 13) return `${Seat}: has ${cardCount} card${cardCount === 1 ? '' : 's'}, expected 13.`;
  }
  return null;
}

function renderTable(result) {
  const lines = result.split('\n').filter(Boolean);
  let html = '<table><tr><th></th><th>South</th><th>North</th><th>West</th><th>East</th></tr>';
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    const strain = parts[0];
    const tricks = parts.slice(1, 5);
    html += '<tr><td>' + (STRAIN_LABELS[strain] || strain) + '</td>' +
      tricks.map(t => `<td>${t}</td>`).join('') + '</tr>';
  }
  html += '</table>';
  tableEl.innerHTML = html;
}

// Shuffles a fresh 52-card deck and deals 13 cards to each seat, formatted
// as "SSSS HHHH DDDD CCCC" (ranks high to low, '-' for a void suit).
function randomDeal() {
  const deck = [];
  for (let suit = 0; suit < 4; ++suit)
    for (const rank of RANKS) deck.push([suit, rank]);

  for (let i = deck.length - 1; i > 0; --i) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }

  const hands = {};
  SEATS.forEach((seat, s) => {
    const bySuit = [[], [], [], []];
    for (const [suit, rank] of deck.slice(s * 13, s * 13 + 13)) bySuit[suit].push(rank);
    hands[seat] = bySuit
      .map(ranks => ranks.sort((a, b) => RANKS.indexOf(a) - RANKS.indexOf(b)))
      .map(ranks => ranks.length ? ranks.join('') : '-')
      .join(' ');
  });
  return hands;
}

dealBtn.addEventListener('click', () => {
  const hands = randomDeal();
  for (const seat of SEATS) document.getElementById(seat).value = hands[seat];
  tableEl.innerHTML = '';
});

// Parses the deal layouts used by hard_deals/, freak_deals/, etc. Hands
// always appear in North, West, East, South order, but the surrounding
// format varies:
//  - seat letter + suit symbols: "N ♠.. ♥.. ♦.. ♣.."
//  - suit symbols only (no seat letter): "♠.. ♥.. ♦.. ♣.."
//  - plain positional groups: "- Q853 AJ962 KT74", either West and East
//    sharing one line (separated by a wide gap) or each on its own line
//  - optionally followed by trailing metadata lines (trump/lead seat,
//    e.g. "N", "C", "West") that must be ignored
function parseDealFile(text) {
  const positionalSeats = ['north', 'west', 'east', 'south'];
  const hands = {};

  const symbolPattern = /(?:([NWES])\s*)?♠\s*(\S+)\s*♥\s*(\S+)\s*♦\s*(\S+)\s*♣\s*(\S+)/g;
  const seatNames = { N: 'north', W: 'west', E: 'east', S: 'south' };
  const symbolMatches = [...text.matchAll(symbolPattern)];
  if (symbolMatches.length === 4) {
    symbolMatches.forEach((match, i) => {
      const [, seat, spades, hearts, diamonds, clubs] = match;
      hands[seatNames[seat] || positionalSeats[i]] = `${spades} ${hearts} ${diamonds} ${clubs}`;
    });
    if (SEATS.every(seat => hands[seat])) return hands;
  }

  // Plain-text fallback: collect every group of 4 card tokens found, in
  // file order, whether a line holds one hand or two (West and East
  // sharing a line, split on the wide gap between them). Lines that
  // aren't a hand (blank, or a trailing trump/lead-seat annotation)
  // simply don't match and are skipped.
  const isCardGroup = (tokens) =>
    tokens.length === 4 && tokens.every(t => /^(-|[2-9TJQKAX]+)$/i.test(t));

  const blocks = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;
    const gap = line.match(/\s{2,}/);
    if (gap) {
      const left = line.slice(0, gap.index).trim().split(/\s+/);
      const right = line.slice(gap.index + gap[0].length).trim().split(/\s+/);
      if (isCardGroup(left) && isCardGroup(right)) {
        blocks.push(left.join(' '), right.join(' '));
        continue;
      }
    }
    const tokens = line.split(/\s+/);
    if (isCardGroup(tokens)) blocks.push(tokens.join(' '));
  }

  if (blocks.length === 4) {
    positionalSeats.forEach((seat, i) => { hands[seat] = blocks[i]; });
  }
  return hands;
}

for (const { id, dir, label } of DEAL_DIRS) {
  document.getElementById(id).addEventListener('change', (event) => {
    const num = event.target.value;
    const hands = parseDealFile(DEALS[dir][num]);
    if (SEATS.some(seat => !hands[seat])) {
      statusEl.textContent = `Failed to load ${label.toLowerCase()} ${num}: unrecognized deal format`;
      return;
    }
    for (const seat of SEATS) document.getElementById(seat).value = hands[seat];
    tableEl.innerHTML = '';
    statusEl.textContent = `Loaded ${label.toLowerCase()} ${num}.`;
  });
}

solveBtn.addEventListener('click', () => {
  const hands = {};
  for (const seat of SEATS) hands[seat] = document.getElementById(seat).value;

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }

  solveBtn.disabled = true;
  statusEl.textContent = 'Solving…';
  tableEl.innerHTML = '';
  worker.postMessage(['solve', hands]);
});
