// SEATS and SEAT_NAME_BY_LETTER come from deal-parser.js.
const SUIT_LETTERS = ['S', 'H', 'D', 'C'];
const STRAIN_LABELS = { N: 'NT', S: '<span class="black">&spades;</span>',
  H: '<span class="red">&hearts;</span>', D: '<span class="red">&diams;</span>',
  C: '<span class="black">&clubs;</span>' };
const VALID_CHARS = /^[AaKkQqJjTt1098765432Xx\- ]*$/;
const VALID_RANKS = new Set(['2','3','4','5','6','7','8','9','T','J','Q','K','A','X']);

const RANKS = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];
// Deal collections to offer in one Sample deal select, one optgroup each,
// backed by DEALS (see deals.js, generated by gen_deals.py from deals/hard/
// and deals/freak/). `short` names options (e.g. "Hard 19") to keep the
// select narrow; `label` is for status messages.
const DEAL_DIRS = [
  { dir: 'freak', label: 'Freak deal', short: 'Freak' },
  { dir: 'hard', label: 'Hard deal', short: 'Hard' },
];
const sampleDealEl = document.getElementById('sampleDeal');

const dealBtn = document.getElementById('deal');
const solveBtn = document.getElementById('solve');
const shuffle10Btn = document.getElementById('shuffle10');
const shuffle100Btn = document.getElementById('shuffle100');
const statusEl = document.getElementById('status');
const tableEl = document.getElementById('table');
const tableHintEl = document.getElementById('tableHint');
const shuffleTableEl = document.getElementById('shuffleTable');
const tablesColumnEl = document.getElementById('tablesColumn');

// On wide screens .tables-column sizes to its content (see index.html), so
// clearing it back to empty -- at the start of every solve/shuffle, or on a
// new deal -- would collapse it to 0 width and shift the deal column
// sideways as the centered flex row re-centers. Track the widest a table
// has actually rendered at and never let the column shrink past that.
const wideLayoutQuery = window.matchMedia('(min-width: 1280px)');
let tablesColumnMinWidth = 0;
function growTablesColumnMinWidth() {
  // Deferred a frame: right after a table's markup is inserted, an
  // auto-layout <table> can still be mid-convergence (its shrink-to-fit
  // width depends on its container's width, which depends on the table's
  // own width), so reading scrollWidth synchronously here can catch an
  // intermediate, too-narrow layout pass instead of the settled one.
  requestAnimationFrame(() => {
    // Below the breakpoint .tables-column is a plain stacked block that's
    // stretched to its container's full width (not sized to its content),
    // so scrollWidth there reflects that stretch, not the table's real
    // width -- recording it would over-reserve space once the layout
    // switches to two columns and push the deal column off-screen.
    if (!wideLayoutQuery.matches) return;
    const width = tablesColumnEl.scrollWidth;
    if (width <= tablesColumnMinWidth) return;
    tablesColumnMinWidth = width;
    document.documentElement.style.setProperty('--tables-min-width', width + 'px');
  });
}

// Matches shuffle.py's CLI default.
const SHUFFLE_MIN_TRICKS = 7;

// Shuffle results accumulate across button presses (10 then 100 -> 110
// total) as long as the hands being shuffled haven't changed since;
// `shuffleHandsKey` is what detects that they have.
let shuffleAccumulator = null;
let shuffleHandsKey = null;

function clearShuffleResults() {
  shuffleAccumulator = null;
  shuffleHandsKey = null;
  shuffleFolded.ew = false;
  shuffleFolded.ns = false;
  shuffleTableEl.innerHTML = '';
}

function mergeShuffleData(acc, batch) {
  if (!acc) return batch;
  const merged = {
    rounds: acc.rounds + batch.rounds,
    elapsedMs: acc.elapsedMs + batch.elapsedMs,
    ew: {},
    ns: {},
  };
  for (const key of ['ew', 'ns']) {
    const counts = {};
    for (const d of ['S', 'N', 'W', 'E'])
      counts[d] = acc[key].counts[d].map((row, r) => row.map((v, t) => v + batch[key].counts[d][r][t]));
    merged[key] = { counts };
  }
  return merged;
}

for (const { dir, short } of DEAL_DIRS) {
  const group = document.createElement('optgroup');
  group.label = short;
  const nums = Object.keys(DEALS[dir]).map(Number).sort((a, b) => a - b);
  for (const n of nums) {
    const option = document.createElement('option');
    option.value = `${dir}:${n}`;
    option.textContent = `${short} ${n}`;
    group.appendChild(option);
  }
  sampleDealEl.appendChild(group);
}

// Solve/solve_plays run in `worker`; Shuffle runs across a pool of
// `shuffleWorkers` (each its own wasm instance/memory, so their
// discard_suit_bottom fast-solve caches can never be reused by
// solve_plays()'s exact-precision cache), so a batch's rounds run across
// the machine's cores in parallel instead of one at a time.
const worker = new Worker('worker.js?v=c6919d5c');
// hardwareConcurrency counts logical (SMT) threads; solving is CPU/cache-
// bound, and README.md's own multi-core benchmark shows SMT buys almost
// nothing for it (8 physical cores -> 16 SMT threads only takes the
// speed-up from 5.2x to 6.3x), so target physical cores (/2, the common
// case on x86) rather than one worker per logical thread -- that
// benchmark says nothing about scaling across *more* physical cores, so
// this isn't otherwise capped. A browser without hardwareConcurrency at
// all is likely on old, low-core hardware, hence the low (not 8) fallback.
// ?workers=N overrides the default, for timing pool sizes per device.
const workersParam = parseInt(new URLSearchParams(location.search).get('workers'), 10);
const SHUFFLE_WORKER_COUNT = workersParam > 0 ? workersParam
  : Math.max(1, Math.floor((navigator.hardwareConcurrency || 4) / 2));
const shuffleWorkers =
  Array.from({ length: SHUFFLE_WORKER_COUNT }, () => new Worker('shuffle-worker.js?v=4919d8b5'));

// Solve and Shuffle share one busy/idle state: entering hands and running
// either one are mutually exclusive, so this covers both directions.
function setBusyState(busy) {
  solveBtn.disabled = busy;
  shuffle10Btn.disabled = busy;
  shuffle100Btn.disabled = busy;
  setEntryDisabled(busy);
}

// Every worker loads its own wasm module independently; only report ready
// once all of them have, since a shuffle batch can land on any pool member.
let workerReady = false;
let shuffleWorkersReadyCount = 0;
function maybeReportReady() {
  const shuffleReady = shuffleWorkersReadyCount === shuffleWorkers.length;
  if (workerReady && shuffleReady) {
    statusEl.textContent = pendingUrlPlay
      ? 'Ready. Click Solve to continue the play from the link.' : 'Ready.';
  }
}

worker.onmessage = (event) => {
  const [type, ...rest] = event.data;
  switch (type) {
    case 'ready':
      solveBtn.disabled = false;
      workerReady = true;
      maybeReportReady();
      if (playsOnReady && playState) requestPlays();
      break;
    case 'abort':
      statusEl.textContent = 'Solver crashed: ' + rest[0];
      setBusyState(false);
      break;
    case 'error': {
      const [errType, message] = rest;
      statusEl.textContent = 'Solver error: ' + message;
      if (errType === 'solve' || errType === 'solve_plays') setBusyState(false);
      break;
    }
    case 'solve': {
      const [result, elapsedMs] = rest;
      showDdTable(result);
      statusEl.textContent = `Solved in ${elapsedMs.toFixed(0)} ms.`;
      setBusyState(false);
      resumeUrlPlay();
      break;
    }
    case 'solve_plays': {
      const [result, , requestId] = rest;
      onSolvePlays(result, requestId);
      break;
    }
  }
};

// A shuffle batch currently in flight across the pool (null when idle).
// Each pool worker gets its own slice of the requested round count (see
// runShuffleBatch()) and reports back independently; this folds their
// partial results together the same way mergeShuffleData() already folds
// separate button-press batches, and tracks combined progress/timing.
let pendingBatch = null;

function workersLabel(n) {
  return ` (${n} worker${n === 1 ? '' : 's'})`;
}

// Dispatch always uses a prefix shuffleWorkers[0..workersToUse-1] of the
// pool (see runShuffleBatch()), so a message's workerIndex here is always
// a valid index into pendingBatch.doneByWorker.
shuffleWorkers.forEach((shuffleWorker, workerIndex) => {
  shuffleWorker.onmessage = (event) => {
    const [type, ...rest] = event.data;
    switch (type) {
      case 'ready':
        ++shuffleWorkersReadyCount;
        if (shuffleWorkersReadyCount === shuffleWorkers.length) {
          shuffle10Btn.disabled = false;
          shuffle100Btn.disabled = false;
        }
        maybeReportReady();
        break;
      case 'abort':
        statusEl.textContent = 'Solver crashed: ' + rest[0];
        pendingBatch = null;
        setBusyState(false);
        break;
      case 'error': {
        const [, message] = rest;
        statusEl.textContent = 'Solver error: ' + message;
        pendingBatch = null;
        setBusyState(false);
        break;
      }
      case 'shuffle_progress': {
        if (!pendingBatch) break;
        const [done] = rest;
        pendingBatch.doneByWorker[workerIndex] = done;
        const totalDone = pendingBatch.doneByWorker.reduce((a, b) => a + b, 0);
        statusEl.textContent = `Shuffling… ${totalDone}/${pendingBatch.totalUnits}${workersLabel(pendingBatch.workers)}`;
        break;
      }
      case 'shuffle': {
        if (!pendingBatch) break;
        const [data] = rest;
        pendingBatch.merged = mergeShuffleData(pendingBatch.merged, data);
        if (--pendingBatch.workersRemaining > 0) break;
        // Wall-clock time for the whole parallel batch, not the sum of each
        // worker's own elapsedMs (which ran concurrently, not back to back).
        pendingBatch.merged.elapsedMs = performance.now() - pendingBatch.startTime;
        shuffleAccumulator = mergeShuffleData(shuffleAccumulator, pendingBatch.merged);
        renderShuffleTable(shuffleAccumulator);
        growTablesColumnMinWidth();
        const { workers } = pendingBatch;
        pendingBatch = null;
        const { rounds, elapsedMs } = shuffleAccumulator;
        const elapsedS = (elapsedMs / 1000).toFixed(1);
        statusEl.textContent = `Shuffled ${rounds} times each way in ${elapsedS} s${workersLabel(workers)}.`;
        setBusyState(false);
        break;
      }
    }
  };
});

// Splits a hand's suit token (e.g. "KJ1042" or "X") into individual rank
// characters, treating "10" as a single "T" rank.
function parseRanks(token) {
  const ranks = [];
  for (let i = 0; i < token.length; ++i) {
    if (token[i] === '1' && token[i + 1] === '0') {
      ranks.push('T');
      ++i;
    } else {
      ranks.push(token[i].toUpperCase());
    }
  }
  return ranks;
}

// Join/split each seat's four per-suit boxes ("<seat>-S" etc.) and the
// single "SSSS HHHH DDDD CCCC" string the rest of the app uses.
function getHandValue(seat) {
  return SUIT_LETTERS.map(suit => document.getElementById(seat + '-' + suit).value.trim() || '-').join(' ');
}

function setHandValue(seat, value) {
  const suits = value.trim().length ? value.trim().split(/\s+/) : [];
  SUIT_LETTERS.forEach((suit, i) => {
    const token = suits[i];
    document.getElementById(seat + '-' + suit).value = !token || token === '-' ? '' : token;
  });
}

function setHandsDisabled(disabled) {
  for (const seat of SEATS) {
    for (const suit of SUIT_LETTERS) document.getElementById(seat + '-' + suit).disabled = disabled;
  }
  document.getElementById('pasteBox').disabled = disabled;
}

// Locks out anything that could change the deal while a solve is pending,
// so the DD table that eventually comes back always matches the hands
// shown -- otherwise a slow solve plus a mid-solve deal change lets the
// table and the hands (and any contract picked from it) mismatch.
function setEntryDisabled(disabled) {
  dealBtn.disabled = disabled;
  sampleDealEl.disabled = disabled;
  setHandsDisabled(disabled);
}

// Basic client-side validation so obviously bad input (typos, duplicate
// cards, wrong-size hands) is caught before it reaches solve(). The wasm
// side aborts on bad characters or a duplicate card, but silently accepts
// hands of unequal size -- Hands::num_tricks() just reads West's card
// count, with no cross-check against the other three seats -- so a short
// hand doesn't error, it just solves something other than the deal you
// typed.
function validateHands(hands) {
  const seen = new Set();
  for (const seat of SEATS) {
    const Seat = seat[0].toUpperCase() + seat.slice(1);
    const value = hands[seat];
    if (!VALID_CHARS.test(value)) {
      return `${Seat}: only card ranks (2-9,T,J,Q,K,A,X), '-' and spaces are allowed.`;
    }
    const suits = value.trim().length ? value.trim().split(/\s+/) : [];
    let cardCount = 0;
    for (let i = 0; i < suits.length && i < 4; ++i) {
      const token = suits[i];
      if (token === '-') continue;
      for (const rank of parseRanks(token)) {
        if (!VALID_RANKS.has(rank)) return `${Seat}: invalid rank '${rank}'.`;
        ++cardCount;
        if (rank === 'X') continue;
        const card = SUIT_LETTERS[i] + rank;
        if (seen.has(card)) return `Duplicate card: ${card}`;
        seen.add(card);
      }
    }
    if (cardCount !== 13) return `${Seat}: has ${cardCount} card${cardCount === 1 ? '' : 's'}, expected 13.`;
  }
  return null;
}

function showDdTable(result) {
  exitPlay();
  renderTable(result);
  ddFolded = false;
  tableEl.style.display = '';
  growTablesColumnMinWidth();
  updateTableHintText();
  tableHintEl.style.display = 'block';
}

// DECLARER_COLUMNS (declarer-columns.js) maps each DD-table column to its
// declarer; matches solve()'s fixed column order in solver.cc (derived from
// its lead_seats iteration), independent of trump.
function renderTable(result) {
  const lines = result.split('\n').filter(Boolean);
  let html = '<table><tr><th></th><th>South</th><th>North</th><th>West</th><th>East</th></tr>';
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    const strain = parts[0];
    const tricks = parts.slice(1, 5);
    html += '<tr><td>' + (STRAIN_LABELS[strain] || strain) + '</td>' +
      tricks.map((t, i) => `<td class="pick" data-strain="${strain}" ` +
        `data-declarer="${DECLARER_COLUMNS[i]}" data-tricks="${t}">${t}</td>`).join('') +
      '</tr>';
  }
  html += '</table>';
  tableEl.innerHTML = html;
  ddLines = lines;
  renderPar();
}

// Par depends only on the trick results and vulnerability, so changing the
// latter re-renders par without re-solving or re-shuffling.
const vulEl = document.getElementById('vul');
// Outside #table/#shuffleTable's foldable parts, so par stays visible when
// the tables are folded.
const ddParEl = document.getElementById('ddPar');
let ddLines = [];
// PBN of the deal ddLines belong to, so the URL only pairs them with it.
let ddDeal = null;
let vulnerability = 'None';
const VULNERABILITIES = ['None', 'N-S', 'E-W', 'All'];

function clearDdTable() {
  tableEl.innerHTML = '';
  ddLines = [];
  ddDeal = null;
  renderPar();
}

function parText([nsFirst, ewFirst]) {
  const strainLabel = s => STRAIN_LABELS[s];
  const describe = list =>
    `${formatParScore(list)}, ${list.map(c => formatParContract(c, strainLabel)).join(', ')}`;
  if (!nsFirst.length && !ewFirst.length) return '0';
  if (!nsFirst.length || !ewFirst.length) return describe(nsFirst.length ? nsFirst : ewFirst);
  return `${describe(nsFirst)} if N/S bid first; ${describe(ewFirst)} if E/W bid first`;
}

// Stats shown in the shuffle tables, from counts[t] = shuffles taking exactly
// t tricks: the average, and pct[t] = % taking t or more, rounded down.
function trickStats(counts) {
  const total = counts.reduce((a, b) => a + b, 0);
  const avg = counts.reduce((a, n, t) => a + n * t, 0) / total;
  const pct = [];
  let atLeast = 0;
  for (let t = 13; t >= 0; --t) {
    atLeast += counts[t];
    pct[t] = Math.floor(atLeast * 100 / total);
  }
  return { avg, pct };
}

// Per-declarer trick counts by strain, as counts[d][strain]; N/S declarers'
// come from shuffling E/W, and vice versa.
function singleDummyCounts(data) {
  const strains = ['N', 'S', 'H', 'D', 'C'];
  const counts = {};
  for (const [d, key] of [['S', 'ew'], ['N', 'ew'], ['W', 'ns'], ['E', 'ns']]) {
    counts[d] = {};
    strains.forEach((strain, row) => { counts[d][strain] = data[key].counts[d][row]; });
  }
  return counts;
}

function renderPar() {
  updateUrl();
  vulEl.value = vulnerability;
  ddParEl.innerHTML = ddLines.length ? 'DD Par: ' + parText(computePar(ddLines, vulnerability)) : '';
  const sdParEl = document.getElementById('sdPar');
  if (sdParEl && shuffleAccumulator)
    sdParEl.innerHTML = 'SD Par: ' +
      parText(computeSingleDummyPar(singleDummyCounts(shuffleAccumulator), vulnerability));
}

vulEl.addEventListener('change', () => {
  vulnerability = vulEl.value;
  renderPar();
});

// Up/Down cycle with wrap-around; handled here since native selects stop at
// the ends and open the popup instead on macOS.
vulEl.addEventListener('keydown', (event) => {
  const step = { ArrowUp: -1, ArrowDown: 1 }[event.key];
  if (!step) return;
  event.preventDefault();
  const n = VULNERABILITIES.length;
  vulnerability = VULNERABILITIES[(VULNERABILITIES.indexOf(vulnerability) + step + n) % n];
  renderPar();
});

// Shared by this table's fold toggle below and shuffleFolded's further down
// -- the two use different render strategies (see each one's own comment
// for why), but the fold arrow itself is the same idiom either way.
const FOLD_ARROW = (folded) => (folded ? '▸' : '▾');

// tableHintEl's text doubles as the DD table's clickable title; clicking it
// folds/unfolds tableEl. Unlike the shuffle tables, this table's markup
// doesn't depend on fold state, so a plain display toggle is enough --
// no need to re-render.
const DD_HINT_TEXT = 'Double-dummy table: Click a cell to play out that contract.';
let ddFolded = false;

function updateTableHintText() {
  tableHintEl.textContent = FOLD_ARROW(ddFolded) + ' ' + DD_HINT_TEXT;
}

tableHintEl.addEventListener('click', () => {
  ddFolded = !ddFolded;
  tableEl.style.display = ddFolded ? 'none' : '';
  updateTableHintText();
});

tableEl.addEventListener('click', (event) => {
  const cell = event.target.closest('td.pick');
  if (!cell) return;
  startPlay(cell.dataset.strain, cell.dataset.declarer, Number(cell.dataset.tricks));
});

// Shuffles a fresh 52-card deck and deals 13 cards to each seat, formatted
// as "SSSS HHHH DDDD CCCC" (ranks high to low, '-' for a void suit).
function randomDeal() {
  const deck = [];
  for (let suit = 0; suit < 4; ++suit)
    for (const rank of RANKS) deck.push([suit, rank]);

  for (let i = deck.length - 1; i > 0; --i) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }

  const hands = {};
  SEATS.forEach((seat, s) => {
    const bySuit = [[], [], [], []];
    for (const [suit, rank] of deck.slice(s * 13, s * 13 + 13)) bySuit[suit].push(rank);
    hands[seat] = bySuit
      .map(ranks => ranks.sort((a, b) => RANKS.indexOf(a) - RANKS.indexOf(b)))
      .map(ranks => ranks.length ? ranks.join('') : '-')
      .join(' ');
  });
  return hands;
}

// Resets the Sample deal select to its placeholder.
function resetSampleDeal() {
  sampleDealEl.value = '';
}

dealBtn.addEventListener('click', () => {
  exitPlay();
  resetSampleDeal();
  const hands = randomDeal();
  for (const seat of SEATS) setHandValue(seat, hands[seat]);
  clearDdTable();
  tableEl.style.display = '';
  ddFolded = false;
  tableHintEl.style.display = 'none';
  clearShuffleResults();
  pasteBoxEl.value = formatPBN(hands);
  statusEl.textContent = 'Dealt a random hand.';
});

function applyPastedHands(hands) {
  exitPlay();
  resetSampleDeal();
  for (const seat of SEATS) setHandValue(seat, hands[seat]);
  clearDdTable();
  tableEl.style.display = '';
  ddFolded = false;
  tableHintEl.style.display = 'none';
  clearShuffleResults();
  statusEl.textContent = 'Loaded deal.';
}

// A dedicated box, rather than intercepting paste page-wide or reading the
// clipboard directly on some other gesture: both are less predictable
// across browsers (notably Firefox, which doesn't support script-initiated
// clipboard reads) and touch devices, where paste only works inside an
// editable field anyway. Fires on plain `input`, not `paste`, so typing a
// deal in by hand works identically -- no clipboard API involved at all.
//
// An <input>'s value is always one line -- a multi-line paste (e.g. text
// copied off a vugraph page's deal panel) lands here with each newline
// turned into a single space, which parseDealFile is built to tolerate
// (see deal-parser.js), so there's no need to read clipboardData directly
// to see the pre-sanitized original.
const pasteBoxEl = document.getElementById('pasteBox');

// Parses/applies whatever's currently in the box, or reports why not --
// shared by every way of "finishing" here: a paste/drop (below), pressing
// Enter, or just clicking away.
function commitPasteBox() {
  const value = pasteBoxEl.value;
  if (!value.trim()) return;
  const hands = parsePastedDeal(value);
  if (hands) {
    vulnerability = parseVulnerability(value) || vulnerability;
    vulEl.value = vulnerability;
    // Left as-is (not cleared) so the box keeps showing what was actually
    // pasted/typed, as confirmation -- rather than snapping back to the
    // placeholder as if nothing had happened.
    applyPastedHands(hands);
  } else {
    statusEl.textContent = "That doesn't look like a recognized deal format.";
  }
}

pasteBoxEl.addEventListener('input', (event) => {
  // Only a paste or drop -- a single bulk insertion, distinct from typing's
  // one 'input' event per keystroke -- auto-commits immediately. Checking
  // on every keystroke while typing would trigger the moment a *partial*
  // prefix of the last card already happened to look like a complete,
  // valid deal (e.g. "...K10" while still typing "K106"), applying early
  // and blurring the field out from under whoever was still typing.
  if (event.inputType !== 'insertFromPaste' && event.inputType !== 'insertFromDrop') return;
  pasteBoxEl.blur();
});
pasteBoxEl.addEventListener('keydown', (event) => {
  if (event.key === 'Enter') pasteBoxEl.blur();
});
pasteBoxEl.addEventListener('blur', commitPasteBox);

sampleDealEl.addEventListener('change', () => {
  const [dir, num] = sampleDealEl.value.split(':');
  const { label } = DEAL_DIRS.find(d => d.dir === dir);
  const hands = parseDealFile(DEALS[dir][num]);
  if (SEATS.some(seat => !hands[seat])) {
    statusEl.textContent = `Failed to load ${label.toLowerCase()} ${num}: unrecognized deal format`;
    return;
  }
  exitPlay();
  for (const seat of SEATS) setHandValue(seat, hands[seat]);
  clearDdTable();
  tableEl.style.display = '';
  ddFolded = false;
  tableHintEl.style.display = 'none';
  clearShuffleResults();
  pasteBoxEl.value = formatPBN(hands);
  statusEl.textContent = `Loaded ${label.toLowerCase()} ${num}.`;
});

solveBtn.addEventListener('click', () => {
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }

  setBusyState(true);
  statusEl.textContent = 'Solving…';
  clearDdTable();
  ddDeal = formatPBN(hands);
  tableHintEl.style.display = 'none';
  worker.postMessage(['solve', hands]);
});

// Which shuffle sections are folded, keyed by the same 'ew'/'ns' dir used
// as each <h3>'s data-dir -- persists across re-renders (accumulating a
// batch, or toggling a fold) since renderShuffleTable() always rebuilds
// from scratch and reads this each time.
const shuffleFolded = { ew: false, ns: false };

// Renders the two shuffle.py-style tables: shuffling E/W (with N/S fixed)
// shows how South/North's actual hands fare against random opponents, and
// vice versa for shuffling N/S. Each title is clickable to fold/unfold its
// own table (see the click listener below).
function renderShuffleTable(data) {
  const strains = ['N', 'S', 'H', 'D', 'C'];
  const tricksList = [];
  for (let t = SHUFFLE_MIN_TRICKS; t <= 13; ++t) tricksList.push(t);
  const counts = singleDummyCounts(data);

  // Both declarers stay in one table, side by side in each cell as
  // "left/right", so they're still directly comparable at a glance -- but
  // collapsed to one number when they don't differ (common at the high/low
  // ends of the trick range), which also keeps cells narrow enough to fit
  // phone widths without horizontal scrolling.
  const pair = (left, right) => (left === right ? `${left}` : `${left}/${right}`);

  function section(dir, title, leftKey, rightKey) {
    const folded = shuffleFolded[dir];
    const arrow = FOLD_ARROW(folded);
    let html = `<h3 data-dir="${dir}">${arrow} ${title}</h3>`;
    if (folded) return html;

    html += `<table><tr><th>${leftKey}/${rightKey}</th><th>avg</th>`;
    for (const t of tricksList) html += `<th>${t}+</th>`;
    html += '</tr>';
    for (const strain of strains) {
      const left = trickStats(counts[leftKey][strain]);
      const right = trickStats(counts[rightKey][strain]);
      html += `<tr><td>${STRAIN_LABELS[strain]}</td>` +
        `<td>${pair(left.avg.toFixed(1), right.avg.toFixed(1))}</td>`;
      for (const t of tricksList) {
        const leftPct = left.pct[t], rightPct = right.pct[t];
        const cell = leftPct === 0 && rightPct === 0 ? '' : pair(leftPct, rightPct);
        html += `<td>${cell}</td>`;
      }
      html += '</tr>';
    }
    return html + '</table>';
  }

  shuffleTableEl.innerHTML =
    section('ew', 'Single-dummy table: Shuffling East/West.', 'S', 'N') +
    section('ns', 'Single-dummy table: Shuffling North/South.', 'W', 'E') +
    '<p class="par" id="sdPar"></p>';
  renderPar();
}

// Delegated (not attached per-<h3>) since renderShuffleTable() replaces
// those elements outright on every render.
shuffleTableEl.addEventListener('click', (event) => {
  const h3 = event.target.closest('h3');
  if (!h3 || !shuffleAccumulator) return;
  shuffleFolded[h3.dataset.dir] = !shuffleFolded[h3.dataset.dir];
  renderShuffleTable(shuffleAccumulator);
});

function runShuffleBatch(rounds) {
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }
  // solve()/shuffle_and_solve()'s hand parsing assumes single-char ranks
  // (no "10", no "X" wildcards); resolveWildcards() normalizes both
  // unconditionally.
  const resolvedHands = resolveWildcards(hands);

  // Results accumulate across presses, but only for the same hands -- reset
  // if they've changed (new deal, edited card, etc.) since the last batch.
  const handsKey = SEATS.map(seat => resolvedHands[seat]).join('|');
  if (handsKey !== shuffleHandsKey) {
    clearShuffleResults();
    shuffleHandsKey = handsKey;
  }

  exitPlay();
  setBusyState(true);

  // Split rounds as evenly as possible across the pool -- capped to
  // `rounds` itself so a small batch (e.g. Shuffle 10 on a many-core
  // machine) doesn't spin up workers that would get 0 rounds.
  const workersToUse = Math.min(shuffleWorkers.length, rounds);
  const baseRounds = Math.floor(rounds / workersToUse);
  const extraRounds = rounds % workersToUse;

  pendingBatch = {
    totalUnits: rounds * 2, // *2 for the ew/ns directions, like shuffle-worker.js's own `total`
    doneByWorker: new Array(workersToUse).fill(0),
    merged: null,
    workers: workersToUse,
    workersRemaining: workersToUse,
    startTime: performance.now(),
  };

  statusEl.textContent = `Shuffling… 0/${pendingBatch.totalUnits}${workersLabel(workersToUse)}`;
  for (let i = 0; i < workersToUse; ++i) {
    const workerRounds = baseRounds + (i < extraRounds ? 1 : 0);
    shuffleWorkers[i].postMessage(['shuffle', resolvedHands, workerRounds]);
  }
}

shuffle10Btn.addEventListener('click', () => runShuffleBatch(10));
shuffle100Btn.addEventListener('click', () => runShuffleBatch(100));

// --- CARD PLAY ---
// Trump encoding expected by solve_plays (see solver.cc:
// enum { SPADE, HEART, DIAMOND, CLUB, NUM_SUITS, NOTRUMP = NUM_SUITS }).
const TRUMP_NUMBERS = { S: 0, H: 1, D: 2, C: 3, N: 4 };
// Rank value for comparing cards within a suit (A high).
const RANK_VALUE = Object.fromEntries(RANKS.map((r, i) => [r, RANKS.length - i]));

const handsEl = document.getElementById('hands');
const centerEl = document.getElementById('center');
const seatCardsEls = Object.fromEntries(SEATS.map(seat => [seat, document.getElementById(seat + '-cards')]));
const seatLabelEls = Object.fromEntries(SEATS.map(seat => [seat, document.querySelector(`.seat.${seat} label`)]));
const playBarEl = document.getElementById('playBar');
const playStatusEl = document.getElementById('playStatus');
const entryHintEl = document.getElementById('entryHint');
const playHintEl = document.getElementById('playHint');
const controlsEl = document.getElementById('controls');
const undoBtn = document.getElementById('undo');
const undoTrickBtn = document.getElementById('undoTrick');
const editHandsBtn = document.getElementById('editHands');

// Active play session, or null when not playing. `history` entries are
// tagged `auto: true` when solve_plays left no real choice. `pendingPlays`
// is the card->diff map for the seat on lead, once the worker answers.
let playState = null;
let playRequestId = 0;

function nextSeat(seat) {
  return SEATS[(SEATS.indexOf(seat) + 1) % 4];
}

function displayRank(rank) {
  return rank === 'T' ? '10' : rank;
}

// "10" is two characters where every other rank is one; tighten it (.ten,
// see CSS) rather than widening every card box to fit it.
function rankHtml(rank) {
  return rank === 'T' ? '<span class="ten">10</span>' : rank;
}

function cardStr(card) {
  return card.suit + card.rank;
}

// Splits an already-validated hand string into its 13 {suit, rank} cards.
function parseHandCards(value) {
  const suits = value.trim().length ? value.trim().split(/\s+/) : [];
  const cards = [];
  for (let i = 0; i < 4 && i < suits.length; ++i) {
    const token = suits[i];
    if (token === '-') continue;
    for (const rank of parseRanks(token)) cards.push({ suit: SUIT_LETTERS[i], rank });
  }
  return cards;
}

// Mirrors ParseHand() in solver.cc: each X becomes the lowest unclaimed
// rank in its suit, walking seats West/North/East/South and suits
// Spades/Hearts/Diamonds/Clubs, left to right.
function resolveWildcards(hands) {
  const used = new Set();
  const resolved = {};
  for (const seat of SEATS) {
    const suits = hands[seat].trim().length ? hands[seat].trim().split(/\s+/) : [];
    const outSuits = [];
    for (let i = 0; i < 4; ++i) {
      const token = suits[i];
      if (!token || token === '-') {
        outSuits.push('-');
        continue;
      }
      const outRanks = parseRanks(token).map(rank => {
        if (rank !== 'X') {
          used.add(SUIT_LETTERS[i] + rank);
          return rank;
        }
        for (let r = RANKS.length - 1; r >= 0; --r) {
          const candidate = SUIT_LETTERS[i] + RANKS[r];
          if (!used.has(candidate)) {
            used.add(candidate);
            return RANKS[r];
          }
        }
        return rank;  // unreachable: suit already holds all 13 ranks
      });
      outSuits.push(outRanks.join(''));
    }
    resolved[seat] = outSuits.join(' ');
  }
  return resolved;
}

function winningCard(trick, trumpLetter) {
  let best = trick[0];
  for (const card of trick.slice(1)) {
    const beats = card.suit === best.suit
      ? RANK_VALUE[card.rank] > RANK_VALUE[best.rank]
      : card.suit === trumpLetter;
    if (beats) best = card;
  }
  return best;
}

// Replays history to derive whose turn it is, the score, and the current
// trick. Recomputing keeps undo trivial (just shorten history and replay).
function replayState() {
  let seat = playState.leadSeat;
  let nsTricks = 0, ewTricks = 0;
  let trick = [];
  let lastTrick = [];
  for (const play of playState.history) {
    trick.push(play);
    if (trick.length === 4) {
      const winner = winningCard(trick, playState.trumpLetter).seat;
      if (winner === 'north' || winner === 'south') ++nsTricks; else ++ewTricks;
      seat = winner;
      lastTrick = trick;
      trick = [];
    } else {
      seat = nextSeat(seat);
    }
  }
  // Keep showing the just-finished trick until the next one's first card.
  return { seat, nsTricks, ewTricks, trick: trick.length ? trick : lastTrick };
}

function remainingCards(seat) {
  const played = new Set(playState.history.filter(p => p.seat === seat).map(cardStr));
  return playState.hands[seat].filter(c => !played.has(cardStr(c)));
}

// level is clamped to >= 1 in startPlay (tricks-6 can be <1, but there's
// no such bid); shortfall shows how far below that clamped level tricks falls.
function contractLabel(level, tricks, strainHtml) {
  const shortfall = (6 + level) - tricks;
  if (shortfall <= 0) return `${level}${strainHtml}`;
  return `${level}${strainHtml}-${shortfall}`;
}

function renderDiffLabel(diff) {
  const n = Number(diff);
  if (n === 0) return '<span class="diff zero">=</span>';
  if (n > 0) return `<span class="diff plus">+${n}</span>`;
  return `<span class="diff minus">–${-n}</span>`;
}

// `plays` is this seat's card->diff map if it's their turn and answered,
// else null/undefined -> cards render plain and unclickable.
function renderSeatCards(seat, plays) {
  const container = seatCardsEls[seat];
  container.innerHTML = '';
  const bySuit = { S: [], H: [], D: [], C: [] };
  for (const card of remainingCards(seat)) bySuit[card.suit].push(card);
  for (const suit of SUIT_LETTERS) bySuit[suit].sort((a, b) => RANK_VALUE[b.rank] - RANK_VALUE[a.rank]);

  // Pad every row to the same slot count (a void suit's "-" counts as one,
  // and 4 is the floor even if every suit is shorter) so East's
  // right-anchored rows still line up their suit symbols.
  const maxSlots = Math.max(4, ...SUIT_LETTERS.map(suit => bySuit[suit].length || 1));

  for (const suit of SUIT_LETTERS) {
    const cards = bySuit[suit];
    const row = document.createElement('div');
    row.className = 'suit-row';
    const label = document.createElement('span');
    label.className = 'suit-symbol';
    label.innerHTML = STRAIN_LABELS[suit];
    row.appendChild(label);

    if (cards.length === 0) {
      const span = document.createElement('span');
      span.className = 'card';
      span.textContent = '-';
      row.appendChild(span);
    } else if (plays && cardStr(cards[0]) in plays) {
      // This suit is the one the seat may legally play from. Every card is
      // clickable; cards within an equivalent run share the same diff as
      // the run's top card (the only one solve_plays reports directly).
      let prevDiff;
      for (const card of cards) {
        const key = cardStr(card);
        const diff = key in plays ? plays[key] : prevDiff;
        const span = document.createElement('span');
        span.className = 'card playable';
        span.innerHTML = rankHtml(card.rank) + renderDiffLabel(diff);
        span.onclick = () => playCard(seat, card);
        row.appendChild(span);
        prevDiff = diff;
      }
    } else {
      for (const card of cards) {
        const span = document.createElement('span');
        span.className = 'card';
        span.innerHTML = rankHtml(card.rank);
        row.appendChild(span);
      }
    }
    for (let i = (cards.length || 1); i < maxSlots; i++) {
      const span = document.createElement('span');
      span.className = 'card pad';
      row.appendChild(span);
    }
    container.appendChild(row);
    // Only fade the edge when the row actually overflows.
    if (row.scrollWidth > row.clientWidth) row.classList.add('scrollable');
  }
}

function renderTrickCenter(trick) {
  centerEl.classList.add('trick-grid');
  centerEl.innerHTML = '<div class="logo"><img class="center-logo" src="favicon.svg" alt=""></div>';
  for (const seat of SEATS) {
    const div = document.createElement('div');
    const playIndex = trick.findIndex(p => p.seat === seat);
    const play = playIndex >= 0 ? trick[playIndex] : null;
    div.className = seat[0] + (play ? ' played' : '');
    div.innerHTML = play
      ? STRAIN_LABELS[play.suit] + '<span class="gap"></span>' + rankHtml(play.rank)
      : '';
    // Grid position is fixed by seat (n/w/e/s), not play order, so when
    // adjacent cards overlap at narrow widths, stack later plays on top.
    if (play) div.style.zIndex = playIndex + 1;
    centerEl.appendChild(div);
  }
}

// West/East's cards are anchored to their column's left/right edge, at a
// position that shifts with the longest suit in the hand (see maxSlots in
// renderSeatCards); nudge the label to sit (plus 1em) past the 2nd card of
// the top suit row so it tracks that shift instead of the label's own
// centering.
function positionSideLabel(seat) {
  const label = seatLabelEls[seat];
  label.style.transform = '';
  const slots = seatCardsEls[seat].querySelector('.suit-row').querySelectorAll('.card');
  if (slots.length < 2) return;
  const labelRect = label.getBoundingClientRect();
  const targetRect = slots[1].getBoundingClientRect();
  const em = parseFloat(getComputedStyle(label).fontSize);
  const shift = (targetRect.left + targetRect.width / 2) - (labelRect.left + labelRect.width / 2) + em;
  label.style.transform = `translateX(${shift}px)`;
}

function renderPlay() {
  updateUrl();
  const state = replayState();
  for (const seat of SEATS) {
    renderSeatCards(seat, seat === state.seat ? playState.pendingPlays : null);
  }
  positionSideLabel('west');
  positionSideLabel('east');
  renderTrickCenter(state.trick);

  const declarerLabel = playState.declarer[0].toUpperCase() + playState.declarer.slice(1);
  const done = playState.history.length === 52;
  playStatusEl.innerHTML =
    `<div>${contractLabel(playState.level, playState.tricks, STRAIN_LABELS[playState.strain])} by ${declarerLabel}${done ? ' (final)' : ''}</div>` +
    `<div>NS ${state.nsTricks} &ndash; EW ${state.ewTricks}</div>`;

  undoBtn.disabled = !playState.history.some(p => !p.auto);
  undoTrickBtn.disabled = playState.history.length === 0;
}

// Set when play starts (e.g. from a link) before the solver has loaded.
let playsOnReady = false;

function requestPlays() {
  playsOnReady = !workerReady;
  if (playsOnReady) return;
  ++playRequestId;
  playState.requestId = playRequestId;
  const playedStr = playState.history.map(cardStr).join('');
  worker.postMessage(['solve_plays', playState.handStrings, playState.level,
    TRUMP_NUMBERS[playState.strain], SEATS.indexOf(playState.leadSeat), playedStr,
    playState.requestId]);
}

function playCardInternal(seat, card, auto) {
  playState.history.push({ seat, suit: card.suit, rank: card.rank, auto });
  playState.pendingPlays = null;
  playState.autoPlay = true;
  renderPlay();
  if (playState.history.length < 52) requestPlays();
}

function playCard(seat, card) {
  if (!playState) return;
  playCardInternal(seat, card, false);
}

function onSolvePlays(result, requestId) {
  if (!playState || requestId !== playState.requestId) return;  // stale response
  const plays = {};
  for (const token of result.trim().split(/\s+/)) {
    if (!token) continue;
    const [card, diff] = token.split(':');
    plays[card] = diff;
  }
  const cardStrs = Object.keys(plays);
  if (cardStrs.length === 0) return;
  const state = replayState();
  if (cardStrs.length === 1 && playState.autoPlay) {
    // Only one meaningful choice -- play it automatically, except right
    // after an undo, which would otherwise just replay it.
    const c = cardStrs[0];
    playCardInternal(state.seat, { suit: c[0], rank: c[1] }, true);
  } else {
    playState.pendingPlays = plays;
    renderPlay();
  }
}

function undo() {
  if (!playState) return;
  // Undo trailing auto-plays too, so one click lands back at a real choice.
  while (playState.history.length > 0 && playState.history[playState.history.length - 1].auto) {
    playState.history.pop();
  }
  if (playState.history.length > 0) playState.history.pop();
  playState.pendingPlays = null;
  playState.autoPlay = false;
  renderPlay();
  requestPlays();
}

// Rewinds to the start of the trick currently in progress, or the last
// completed trick if none is (undo() rewinds one card at a time; this is
// the fast, trick-at-a-time version).
function undoTrick() {
  if (!playState || playState.history.length === 0) return;
  const trickStart = Math.floor((playState.history.length - 1) / 4) * 4;
  playState.history.length = trickStart;
  playState.pendingPlays = null;
  playState.autoPlay = false;
  renderPlay();
  requestPlays();
}

function setPlayModeUI(active) {
  playBarEl.style.display = active ? 'flex' : 'none';
  playStatusEl.style.display = active ? 'block' : 'none';
  entryHintEl.style.display = active ? 'none' : '';
  document.getElementById('pasteBar').style.display = active ? 'none' : '';
  playHintEl.style.display = active ? 'block' : 'none';
  controlsEl.style.display = active ? 'none' : 'flex';
  setHandsDisabled(active);
  dealBtn.disabled = active;
  solveBtn.disabled = active;
  sampleDealEl.disabled = active;
}

function exitPlay() {
  if (!playState) return;
  playState = null;
  handsEl.classList.remove('playing');
  centerEl.classList.remove('trick-grid');
  centerEl.innerHTML = '<img class="center-logo" src="favicon.svg" alt="">';
  seatLabelEls.west.style.transform = '';
  seatLabelEls.east.style.transform = '';
  setPlayModeUI(false);
  updateUrl();
}

// `cards` (e.g. "CASQ", from a link) are played first, stopping at the first
// one that isn't legal, so the solver is only asked about the position after.
function startPlay(strain, declarer, tricks, cards = '') {
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }
  // Card play needs concrete cards, so resolve any X wildcards first.
  const resolvedHands = SEATS.some(seat => /x/i.test(hands[seat])) ? resolveWildcards(hands) : hands;

  const parsedHands = {};
  for (const seat of SEATS) parsedHands[seat] = parseHandCards(resolvedHands[seat]);

  playState = {
    handStrings: resolvedHands,
    hands: parsedHands,
    strain,
    trumpLetter: strain === 'N' ? null : strain,
    level: Math.max(1, tricks - 6),
    tricks,
    declarer,
    leadSeat: nextSeat(declarer),
    history: [],
    pendingPlays: null,
    // Off for the first answer after an undo, so it doesn't just replay.
    autoPlay: true,
    requestId: 0,
  };

  for (const card of cards.toUpperCase().match(/[SHDC][2-9TJQKA]/g) || []) {
    const history = playState.history;
    const { seat } = replayState();
    const remaining = remainingCards(seat);
    if (!remaining.some(c => cardStr(c) === card)) break;
    const led = history.length % 4 ? history[history.length - history.length % 4].suit : null;
    if (led && card[0] !== led && remaining.some(c => c.suit === led)) break;
    history.push({ seat, suit: card[0], rank: card[1], auto: false });
  }

  handsEl.classList.add('playing');
  setPlayModeUI(true);

  renderPlay();
  if (playState.history.length < 52) requestPlays();
}

undoBtn.addEventListener('click', undo);
undoTrickBtn.addEventListener('click', undoTrick);
editHandsBtn.addEventListener('click', exitPlay);

// --- Shareable URL ---
// The URL hash mirrors the deal, vulnerability, DD table and any play in
// progress, e.g. #deal=<PBN>&vul=N-S&dd=<20 hex digits>&play=NE&cards=CASQ
// (notrump by East, with CA and SQ played), so a copied link reopens the same
// position. dd, the table's trick counts, lets a link show it without
// re-solving; without it, loading a link fills in the deal and the next Solve
// of that same deal resumes the play.
let urlLoaded = false;
let pendingUrlPlay = null;
const DD_STRAINS = ['N', 'S', 'H', 'D', 'C'];

function encodeDd(lines) {
  return lines.map(line => line.trim().split(/\s+/).slice(1, 5)
    .map(n => Number(n).toString(16)).join('')).join('');
}

// Back to solve()'s "<strain> <S> <N> <W> <E>" lines, or null if malformed.
function decodeDd(dd) {
  if (!/^[0-9a-d]{20}$/i.test(dd)) return null;
  const tricks = [...dd].map(c => parseInt(c, 16));
  return DD_STRAINS.map((strain, i) => `${strain} ${tricks.slice(i * 4, i * 4 + 4).join(' ')}`).join('\n');
}

function updateUrl() {
  if (!urlLoaded) return;
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);
  const params = new URLSearchParams();
  const deal = validateHands(hands) ? null : formatPBN(hands);
  if (deal) params.set('deal', deal);
  if (vulnerability !== 'None') params.set('vul', vulnerability);
  if (deal && ddLines.length && ddDeal === deal) params.set('dd', encodeDd(ddLines));
  if (playState) {
    params.set('play', playState.strain + playState.declarer[0].toUpperCase());
    if (playState.history.length) params.set('cards', playState.history.map(cardStr).join(''));
  } else if (pendingUrlPlay && pendingUrlPlay.deal === deal) {
    params.set('play', pendingUrlPlay.play);
    if (pendingUrlPlay.cards) params.set('cards', pendingUrlPlay.cards);
  }
  const hash = params.toString();
  history.replaceState(null, '', hash ? '#' + hash : location.pathname + location.search);
}

function loadFromUrl() {
  const params = new URLSearchParams(location.hash.slice(1));
  urlLoaded = true;
  const deal = params.get('deal');
  if (!deal) return;
  const hands = parsePBN(deal);
  if (!hands || SEATS.some(seat => !hands[seat])) {
    statusEl.textContent = "Couldn't read the deal in the link.";
    return;
  }
  const vul = params.get('vul');
  vulnerability = VULNERABILITIES.includes(vul) ? vul : 'None';
  vulEl.value = vulnerability;
  const play = params.get('play') || '';
  pendingUrlPlay = /^[NSHDC][NSEW]$/.test(play)
    ? { play, deal: formatPBN(hands), cards: params.get('cards') || '' }
    : null;
  applyPastedHands(hands);
  pasteBoxEl.value = formatPBN(hands);
  const dd = decodeDd(params.get('dd') || '');
  if (!dd) {
    statusEl.textContent = pendingUrlPlay
      ? 'Loaded deal from link. Click Solve to continue its play.'
      : 'Loaded deal from link.';
    return;
  }
  // Shown as given; Solve recomputes it.
  ddDeal = formatPBN(hands);
  showDdTable(dd);
  statusEl.textContent = 'Loaded deal and DD table from link.';
  resumeUrlPlay();
}

// Once the link's deal has a DD table (and is unchanged), starts its contract
// with its cards played.
function resumeUrlPlay() {
  const pending = pendingUrlPlay;
  pendingUrlPlay = null;
  if (!pending) return;
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);
  if (formatPBN(hands) !== pending.deal) return;
  const strain = pending.play[0], declarer = SEAT_NAME_BY_LETTER[pending.play[1]];
  const cell = tableEl.querySelector(`td.pick[data-strain="${strain}"][data-declarer="${declarer}"]`);
  if (!cell) return;
  startPlay(strain, declarer, Number(cell.dataset.tricks), pending.cards);
}

window.addEventListener('hashchange', loadFromUrl);
loadFromUrl();
