const SEATS = ['west', 'north', 'east', 'south'];
const SUIT_LETTERS = ['S', 'H', 'D', 'C'];
const STRAIN_LABELS = { N: 'NT', S: '<span class="black">&spades;</span>',
  H: '<span class="red">&hearts;</span>', D: '<span class="red">&diams;</span>',
  C: '<span class="black">&clubs;</span>' };
const VALID_CHARS = /^[AaKkQqJjTt1098765432Xx\- ]*$/;
const VALID_RANKS = new Set(['2','3','4','5','6','7','8','9','T','J','Q','K','A','X']);

const RANKS = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];
// Deal collections to offer, backed by DEALS (see deals.js, generated by
// gen_deals.py from hard_deals/ and freak_deals/).
const DEAL_DIRS = [
  { id: 'freakDealNum', dir: 'freak_deals', label: 'Freak deal' },
  { id: 'hardDealNum', dir: 'hard_deals', label: 'Hard deal' },
];

const dealBtn = document.getElementById('deal');
const solveBtn = document.getElementById('solve');
const statusEl = document.getElementById('status');
const tableEl = document.getElementById('table');

for (const { id, dir, label } of DEAL_DIRS) {
  const select = document.getElementById(id);
  const nums = Object.keys(DEALS[dir]).map(Number).sort((a, b) => a - b);
  for (const n of nums) {
    const option = document.createElement('option');
    option.value = n;
    option.textContent = `${label} ${n}`;
    select.appendChild(option);
  }
}

const worker = new Worker('worker.js');

worker.onmessage = (event) => {
  const [type, ...rest] = event.data;
  switch (type) {
    case 'ready':
      solveBtn.disabled = false;
      statusEl.textContent = 'Ready.';
      break;
    case 'abort':
      statusEl.textContent = 'Solver crashed: ' + rest[0];
      solveBtn.disabled = false;
      break;
    case 'solve': {
      const [result, elapsedMs] = rest;
      exitPlay();
      renderTable(result);
      tableHintEl.style.display = 'block';
      statusEl.textContent = `Solved in ${elapsedMs.toFixed(0)} ms.`;
      solveBtn.disabled = false;
      break;
    }
    case 'solve_plays': {
      const [result, , requestId] = rest;
      onSolvePlays(result, requestId);
      break;
    }
  }
};

// Splits a hand's suit token (e.g. "KJ1042" or "X") into individual rank
// characters, treating "10" as a single "T" rank.
function parseRanks(token) {
  const ranks = [];
  for (let i = 0; i < token.length; ++i) {
    if (token[i] === '1' && token[i + 1] === '0') {
      ranks.push('T');
      ++i;
    } else {
      ranks.push(token[i].toUpperCase());
    }
  }
  return ranks;
}

// Join/split each seat's four per-suit boxes ("<seat>-S" etc.) and the
// single "SSSS HHHH DDDD CCCC" string the rest of the app uses.
function getHandValue(seat) {
  return SUIT_LETTERS.map(suit => document.getElementById(seat + '-' + suit).value.trim() || '-').join(' ');
}

function setHandValue(seat, value) {
  const suits = value.trim().length ? value.trim().split(/\s+/) : [];
  SUIT_LETTERS.forEach((suit, i) => {
    const token = suits[i];
    document.getElementById(seat + '-' + suit).value = !token || token === '-' ? '' : token;
  });
}

function setHandsDisabled(disabled) {
  for (const seat of SEATS) {
    for (const suit of SUIT_LETTERS) document.getElementById(seat + '-' + suit).disabled = disabled;
  }
}

// Basic client-side validation so obviously bad input (typos, duplicate
// cards, wrong-size hands) is caught before it reaches solve(). The wasm
// side aborts on bad characters or a duplicate card, but silently accepts
// hands of unequal size -- Hands::num_tricks() just reads West's card
// count, with no cross-check against the other three seats -- so a short
// hand doesn't error, it just solves something other than the deal you
// typed.
function validateHands(hands) {
  const seen = new Set();
  for (const seat of SEATS) {
    const Seat = seat[0].toUpperCase() + seat.slice(1);
    const value = hands[seat];
    if (!VALID_CHARS.test(value)) {
      return `${Seat}: only card ranks (2-9,T,J,Q,K,A,X), '-' and spaces are allowed.`;
    }
    const suits = value.trim().length ? value.trim().split(/\s+/) : [];
    let cardCount = 0;
    for (let i = 0; i < suits.length && i < 4; ++i) {
      const token = suits[i];
      if (token === '-') continue;
      for (const rank of parseRanks(token)) {
        if (!VALID_RANKS.has(rank)) return `${Seat}: invalid rank '${rank}'.`;
        ++cardCount;
        if (rank === 'X') continue;
        const card = SUIT_LETTERS[i] + rank;
        if (seen.has(card)) return `Duplicate card: ${card}`;
        seen.add(card);
      }
    }
    if (cardCount !== 13) return `${Seat}: has ${cardCount} card${cardCount === 1 ? '' : 's'}, expected 13.`;
  }
  return null;
}

// Declarer for each DD-table column; matches solve()'s fixed column order
// in solver.cc (derived from its lead_seats iteration), independent of trump.
const DECLARER_COLUMNS = ['south', 'north', 'west', 'east'];

function renderTable(result) {
  const lines = result.split('\n').filter(Boolean);
  let html = '<table><tr><th></th><th>South</th><th>North</th><th>West</th><th>East</th></tr>';
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    const strain = parts[0];
    const tricks = parts.slice(1, 5);
    html += '<tr><td>' + (STRAIN_LABELS[strain] || strain) + '</td>' +
      tricks.map((t, i) => `<td class="pick" data-strain="${strain}" ` +
        `data-declarer="${DECLARER_COLUMNS[i]}" data-tricks="${t}">${t}</td>`).join('') +
      '</tr>';
  }
  html += '</table>';
  tableEl.innerHTML = html;
}

tableEl.addEventListener('click', (event) => {
  const cell = event.target.closest('td.pick');
  if (!cell) return;
  startPlay(cell.dataset.strain, cell.dataset.declarer, Number(cell.dataset.tricks));
});

// Shuffles a fresh 52-card deck and deals 13 cards to each seat, formatted
// as "SSSS HHHH DDDD CCCC" (ranks high to low, '-' for a void suit).
function randomDeal() {
  const deck = [];
  for (let suit = 0; suit < 4; ++suit)
    for (const rank of RANKS) deck.push([suit, rank]);

  for (let i = deck.length - 1; i > 0; --i) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }

  const hands = {};
  SEATS.forEach((seat, s) => {
    const bySuit = [[], [], [], []];
    for (const [suit, rank] of deck.slice(s * 13, s * 13 + 13)) bySuit[suit].push(rank);
    hands[seat] = bySuit
      .map(ranks => ranks.sort((a, b) => RANKS.indexOf(a) - RANKS.indexOf(b)))
      .map(ranks => ranks.length ? ranks.join('') : '-')
      .join(' ');
  });
  return hands;
}

// Resets every deal-picker select to its placeholder, except `exceptId`.
function resetDealSelects(exceptId) {
  for (const { id } of DEAL_DIRS) {
    if (id !== exceptId) document.getElementById(id).value = '';
  }
}

dealBtn.addEventListener('click', () => {
  exitPlay();
  resetDealSelects();
  const hands = randomDeal();
  for (const seat of SEATS) setHandValue(seat, hands[seat]);
  tableEl.innerHTML = '';
  tableHintEl.style.display = 'none';
  statusEl.textContent = 'Dealt a random hand.';
});

// Parses the deal layouts used by hard_deals/, freak_deals/, etc. Hands
// always appear in North, West, East, South order, but the surrounding
// format varies:
//  - seat letter + suit symbols: "N ♠.. ♥.. ♦.. ♣.."
//  - suit symbols only (no seat letter): "♠.. ♥.. ♦.. ♣.."
//  - plain positional groups: "- Q853 AJ962 KT74", either West and East
//    sharing one line (separated by a wide gap) or each on its own line
//  - optionally followed by trailing metadata lines (trump/lead seat,
//    e.g. "N", "C", "West") that must be ignored
function parseDealFile(text) {
  const positionalSeats = ['north', 'west', 'east', 'south'];
  const hands = {};

  const symbolPattern = /(?:([NWES])\s*)?♠\s*(\S+)\s*♥\s*(\S+)\s*♦\s*(\S+)\s*♣\s*(\S+)/g;
  const seatNames = { N: 'north', W: 'west', E: 'east', S: 'south' };
  const symbolMatches = [...text.matchAll(symbolPattern)];
  if (symbolMatches.length === 4) {
    symbolMatches.forEach((match, i) => {
      const [, seat, spades, hearts, diamonds, clubs] = match;
      hands[seatNames[seat] || positionalSeats[i]] = `${spades} ${hearts} ${diamonds} ${clubs}`;
    });
    if (SEATS.every(seat => hands[seat])) return hands;
  }

  // Plain-text fallback: collect every group of 4 card tokens found, in
  // file order, whether a line holds one hand or two (West and East
  // sharing a line, split on the wide gap between them). Lines that
  // aren't a hand (blank, or a trailing trump/lead-seat annotation)
  // simply don't match and are skipped.
  const isCardGroup = (tokens) =>
    tokens.length === 4 && tokens.every(t => /^(-|[2-9TJQKAX]+)$/i.test(t));

  const blocks = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;
    const gap = line.match(/\s{2,}/);
    if (gap) {
      const left = line.slice(0, gap.index).trim().split(/\s+/);
      const right = line.slice(gap.index + gap[0].length).trim().split(/\s+/);
      if (isCardGroup(left) && isCardGroup(right)) {
        blocks.push(left.join(' '), right.join(' '));
        continue;
      }
    }
    const tokens = line.split(/\s+/);
    if (isCardGroup(tokens)) blocks.push(tokens.join(' '));
  }

  if (blocks.length === 4) {
    positionalSeats.forEach((seat, i) => { hands[seat] = blocks[i]; });
  }
  return hands;
}

for (const { id, dir, label } of DEAL_DIRS) {
  document.getElementById(id).addEventListener('change', (event) => {
    const num = event.target.value;
    const hands = parseDealFile(DEALS[dir][num]);
    if (SEATS.some(seat => !hands[seat])) {
      statusEl.textContent = `Failed to load ${label.toLowerCase()} ${num}: unrecognized deal format`;
      return;
    }
    exitPlay();
    resetDealSelects(id);
    for (const seat of SEATS) setHandValue(seat, hands[seat]);
    tableEl.innerHTML = '';
    tableHintEl.style.display = 'none';
    statusEl.textContent = `Loaded ${label.toLowerCase()} ${num}.`;
  });
}

solveBtn.addEventListener('click', () => {
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }

  solveBtn.disabled = true;
  statusEl.textContent = 'Solving…';
  tableEl.innerHTML = '';
  tableHintEl.style.display = 'none';
  worker.postMessage(['solve', hands]);
});

// --- CARD PLAY ---
// Trump encoding expected by solve_plays (see solver.cc:
// enum { SPADE, HEART, DIAMOND, CLUB, NUM_SUITS, NOTRUMP = NUM_SUITS }).
const TRUMP_NUMBERS = { S: 0, H: 1, D: 2, C: 3, N: 4 };
// Rank value for comparing cards within a suit (A high).
const RANK_VALUE = Object.fromEntries(RANKS.map((r, i) => [r, RANKS.length - i]));

const handsEl = document.getElementById('hands');
const centerEl = document.getElementById('center');
const seatCardsEls = Object.fromEntries(SEATS.map(seat => [seat, document.getElementById(seat + '-cards')]));
const playBarEl = document.getElementById('playBar');
const playStatusEl = document.getElementById('playStatus');
const entryHintEl = document.getElementById('entryHint');
const playHintEl = document.getElementById('playHint');
const tableHintEl = document.getElementById('tableHint');
const controlsEl = document.getElementById('controls');
const undoBtn = document.getElementById('undo');
const editHandsBtn = document.getElementById('editHands');

// Active play session, or null when not playing. `history` entries are
// tagged `auto: true` when solve_plays left no real choice. `pendingPlays`
// is the card->diff map for the seat on lead, once the worker answers.
let playState = null;
let playRequestId = 0;

function nextSeat(seat) {
  return SEATS[(SEATS.indexOf(seat) + 1) % 4];
}

function displayRank(rank) {
  return rank === 'T' ? '10' : rank;
}

function cardStr(card) {
  return card.suit + card.rank;
}

// Splits an already-validated hand string into its 13 {suit, rank} cards.
function parseHandCards(value) {
  const suits = value.trim().length ? value.trim().split(/\s+/) : [];
  const cards = [];
  for (let i = 0; i < 4 && i < suits.length; ++i) {
    const token = suits[i];
    if (token === '-') continue;
    for (const rank of parseRanks(token)) cards.push({ suit: SUIT_LETTERS[i], rank });
  }
  return cards;
}

// Mirrors ParseHand() in solver.cc: each X becomes the lowest unclaimed
// rank in its suit, walking seats West/North/East/South and suits
// Spades/Hearts/Diamonds/Clubs, left to right.
function resolveWildcards(hands) {
  const used = new Set();
  const resolved = {};
  for (const seat of SEATS) {
    const suits = hands[seat].trim().length ? hands[seat].trim().split(/\s+/) : [];
    const outSuits = [];
    for (let i = 0; i < 4; ++i) {
      const token = suits[i];
      if (!token || token === '-') {
        outSuits.push('-');
        continue;
      }
      const outRanks = parseRanks(token).map(rank => {
        if (rank !== 'X') {
          used.add(SUIT_LETTERS[i] + rank);
          return rank;
        }
        for (let r = RANKS.length - 1; r >= 0; --r) {
          const candidate = SUIT_LETTERS[i] + RANKS[r];
          if (!used.has(candidate)) {
            used.add(candidate);
            return RANKS[r];
          }
        }
        return rank;  // unreachable: suit already holds all 13 ranks
      });
      outSuits.push(outRanks.join(''));
    }
    resolved[seat] = outSuits.join(' ');
  }
  return resolved;
}

function winningCard(trick, trumpLetter) {
  let best = trick[0];
  for (const card of trick.slice(1)) {
    const beats = card.suit === best.suit
      ? RANK_VALUE[card.rank] > RANK_VALUE[best.rank]
      : card.suit === trumpLetter;
    if (beats) best = card;
  }
  return best;
}

// Replays history to derive whose turn it is, the score, and the current
// trick. Recomputing keeps undo trivial (just shorten history and replay).
function replayState() {
  let seat = playState.leadSeat;
  let nsTricks = 0, ewTricks = 0;
  let trick = [];
  let lastTrick = [];
  for (const play of playState.history) {
    trick.push(play);
    if (trick.length === 4) {
      const winner = winningCard(trick, playState.trumpLetter).seat;
      if (winner === 'north' || winner === 'south') ++nsTricks; else ++ewTricks;
      seat = winner;
      lastTrick = trick;
      trick = [];
    } else {
      seat = nextSeat(seat);
    }
  }
  // Keep showing the just-finished trick until the next one's first card.
  return { seat, nsTricks, ewTricks, trick: trick.length ? trick : lastTrick };
}

function remainingCards(seat) {
  const played = new Set(playState.history.filter(p => p.seat === seat).map(cardStr));
  return playState.hands[seat].filter(c => !played.has(cardStr(c)));
}

// level is clamped to >= 1 in startPlay (tricks-6 can be <1, but there's
// no such bid); shortfall shows how far below that clamped level tricks falls.
function contractLabel(level, tricks, strainHtml) {
  const shortfall = (6 + level) - tricks;
  if (shortfall <= 0) return `${level}${strainHtml}`;
  return `${level}${strainHtml}-${shortfall}`;
}

function renderDiffLabel(diff) {
  const n = Number(diff);
  if (n === 0) return '<span class="diff zero">=</span>';
  if (n > 0) return `<span class="diff plus">+${n}</span>`;
  return `<span class="diff minus">–${-n}</span>`;
}

// `plays` is this seat's card->diff map if it's their turn and answered,
// else null/undefined -> cards render plain and unclickable.
function renderSeatCards(seat, plays) {
  const container = seatCardsEls[seat];
  container.innerHTML = '';
  const bySuit = { S: [], H: [], D: [], C: [] };
  for (const card of remainingCards(seat)) bySuit[card.suit].push(card);
  for (const suit of SUIT_LETTERS) bySuit[suit].sort((a, b) => RANK_VALUE[b.rank] - RANK_VALUE[a.rank]);

  for (const suit of SUIT_LETTERS) {
    const cards = bySuit[suit];
    const row = document.createElement('div');
    row.className = 'suit-row';
    const label = document.createElement('span');
    label.className = 'suit-symbol';
    label.innerHTML = STRAIN_LABELS[suit];
    row.appendChild(label);

    if (cards.length === 0) {
      const span = document.createElement('span');
      span.className = 'card';
      span.textContent = '-';
      row.appendChild(span);
    } else if (plays && cardStr(cards[0]) in plays) {
      // This suit is the one the seat may legally play from. Every card is
      // clickable; cards within an equivalent run share the same diff as
      // the run's top card (the only one solve_plays reports directly).
      let prevDiff;
      for (const card of cards) {
        const key = cardStr(card);
        const diff = key in plays ? plays[key] : prevDiff;
        const span = document.createElement('span');
        span.className = 'card playable';
        span.innerHTML = displayRank(card.rank) + renderDiffLabel(diff);
        span.onclick = () => playCard(seat, card);
        row.appendChild(span);
        prevDiff = diff;
      }
    } else {
      for (const card of cards) {
        const span = document.createElement('span');
        span.className = 'card';
        span.textContent = displayRank(card.rank);
        row.appendChild(span);
      }
    }
    container.appendChild(row);
    // Only fade the edge when the row actually overflows.
    if (row.scrollWidth > row.clientWidth) row.classList.add('scrollable');
  }
}

function renderTrickCenter(trick) {
  centerEl.classList.add('trick-grid');
  centerEl.innerHTML = '';
  for (const seat of SEATS) {
    const div = document.createElement('div');
    div.className = seat[0];
    const play = trick.find(p => p.seat === seat);
    div.innerHTML = play
      ? STRAIN_LABELS[play.suit] + '<span class="gap"></span>' + displayRank(play.rank)
      : '';
    centerEl.appendChild(div);
  }
}

function renderPlay() {
  const state = replayState();
  for (const seat of SEATS) {
    renderSeatCards(seat, seat === state.seat ? playState.pendingPlays : null);
  }
  renderTrickCenter(state.trick);

  const declarerLabel = playState.declarer[0].toUpperCase() + playState.declarer.slice(1);
  const done = playState.history.length === 52;
  playStatusEl.innerHTML =
    `<div>${contractLabel(playState.level, playState.tricks, STRAIN_LABELS[playState.strain])} by ${declarerLabel}${done ? ' (final)' : ''}</div>` +
    `<div>NS ${state.nsTricks} &ndash; EW ${state.ewTricks}</div>`;

  undoBtn.disabled = !playState.history.some(p => !p.auto);
}

function requestPlays() {
  ++playRequestId;
  playState.requestId = playRequestId;
  const playedStr = playState.history.map(cardStr).join('');
  worker.postMessage(['solve_plays', playState.handStrings, playState.level,
    TRUMP_NUMBERS[playState.strain], SEATS.indexOf(playState.leadSeat), playedStr,
    playState.requestId]);
}

function playCardInternal(seat, card, auto) {
  playState.history.push({ seat, suit: card.suit, rank: card.rank, auto });
  playState.pendingPlays = null;
  renderPlay();
  if (playState.history.length < 52) requestPlays();
}

function playCard(seat, card) {
  if (!playState) return;
  playCardInternal(seat, card, false);
}

function onSolvePlays(result, requestId) {
  if (!playState || requestId !== playState.requestId) return;  // stale response
  const plays = {};
  for (const token of result.trim().split(/\s+/)) {
    if (!token) continue;
    const [card, diff] = token.split(':');
    plays[card] = diff;
  }
  const cardStrs = Object.keys(plays);
  if (cardStrs.length === 0) return;
  const state = replayState();
  if (cardStrs.length === 1) {
    // Only one meaningful choice -- play it automatically.
    const c = cardStrs[0];
    playCardInternal(state.seat, { suit: c[0], rank: c[1] }, true);
  } else {
    playState.pendingPlays = plays;
    renderPlay();
  }
}

function undo() {
  if (!playState) return;
  // Undo trailing auto-plays too, so one click lands back at a real choice.
  while (playState.history.length > 0 && playState.history[playState.history.length - 1].auto) {
    playState.history.pop();
  }
  if (playState.history.length > 0) playState.history.pop();
  playState.pendingPlays = null;
  renderPlay();
  requestPlays();
}

function setPlayModeUI(active) {
  playBarEl.style.display = active ? 'flex' : 'none';
  playStatusEl.style.display = active ? 'block' : 'none';
  entryHintEl.style.display = active ? 'none' : '';
  playHintEl.style.display = active ? 'block' : 'none';
  controlsEl.style.display = active ? 'none' : 'flex';
  setHandsDisabled(active);
  dealBtn.disabled = active;
  solveBtn.disabled = active;
  for (const { id } of DEAL_DIRS) document.getElementById(id).disabled = active;
}

function exitPlay() {
  if (!playState) return;
  playState = null;
  handsEl.classList.remove('playing');
  centerEl.classList.remove('trick-grid');
  centerEl.innerHTML = '&spades;';
  setPlayModeUI(false);
}

function startPlay(strain, declarer, tricks) {
  const hands = {};
  for (const seat of SEATS) hands[seat] = getHandValue(seat);

  const error = validateHands(hands);
  if (error) {
    statusEl.textContent = error;
    return;
  }
  // Card play needs concrete cards, so resolve any X wildcards first.
  const resolvedHands = SEATS.some(seat => /x/i.test(hands[seat])) ? resolveWildcards(hands) : hands;

  const parsedHands = {};
  for (const seat of SEATS) parsedHands[seat] = parseHandCards(resolvedHands[seat]);

  playState = {
    handStrings: resolvedHands,
    hands: parsedHands,
    strain,
    trumpLetter: strain === 'N' ? null : strain,
    level: Math.max(1, tricks - 6),
    tricks,
    declarer,
    leadSeat: nextSeat(declarer),
    history: [],
    pendingPlays: null,
    requestId: 0,
  };

  handsEl.classList.add('playing');
  setPlayModeUI(true);

  renderPlay();
  requestPlays();
}

undoBtn.addEventListener('click', undo);
editHandsBtn.addEventListener('click', exitPlay);
