// Generated by gen_deals.py -- do not edit by hand.
const DEALS = {
  "freak_deals": {
    "0": "                          ♠ AQT62 ♥ - ♦ Q97 ♣ AT832\n  ♠ J743 ♥ Q9 ♦ KT53 ♣ Q94                       ♠ K85 ♥ KJ753 ♦ - ♣ KJ765\n                          ♠ 9 ♥ AT8642 ♦ AJ8642 ♣ -\n",
    "1": "                  - AJ852 KT74 Q963\nQ963 KT74 - AJ852\n                                  KT74 Q963 AJ852 -\n                  AJ852 - Q963 KT74\n",
    "2": "                   KJ9753 - AQT8642 -\nAQT8642 KJ9753 - -                    - - KJ9753 AQT8642\n                   - AQT8642 - KJ9753\nN\nSouth\n",
    "3": "                  AJ962 KT74 - Q853\nKT74 - Q853 AJ962                   Q853 AJ962 KT74 -\n                  - Q853 AJ962 KT74\nN\nN\n"
  },
  "hard_deals": {
    "1": "                        N ♠ QT ♥ KQT8 ♦ Q9 ♣ QJT62\nW ♠ K742 ♥ AJ72 ♦ 8642 ♣ 8                      E ♠ 8 ♥ 9654 ♦ AK7 ♣ AK953\n                        S ♠ AJ9653 ♥ 3 ♦ JT53 ♣ 74\n",
    "10": "                         N ♠ J432 ♥ J74 ♦ J ♣ AJ952\n W ♠ KT85 ♥ A953 ♦ Q873 ♣ 6                      E ♠ Q9 ♥ QT8 ♦ K965 ♣ K743\n                         S ♠ A76 ♥ K62 ♦ AT42 ♣ QT8\n",
    "11": "                         N ♠ A86 ♥ A742 ♦ KJT74 ♣ 3\n W ♠ T9 ♥ KJT93 ♦ Q86 ♣ A86                      E ♠ Q42 ♥ 8 ♦ A932 ♣ K9752\n                         S ♠ KJ753 ♥ Q65 ♦ 5 ♣ QJT4\n",
    "12": "                         N ♠ KT87 ♥ 84 ♦ A9873 ♣ K5\n W ♠ 63 ♥ A2 ♦ KQT64 ♣ QJ83                      E ♠ Q542 ♥ JT96 ♦ J52 ♣ A9\n                         S ♠ AJ9 ♥ KQ753 ♦ - ♣ T7642\n",
    "13": "              Q974 - K7652 AT76\n3 T972 A98 KJ853          AT86 KQ8543 QJ4 -\n              KJ52 AJ6 T3 Q942\nN\n",
    "14": "            AJ74 - K974 K8762 \nKQT53 K52 - QJ943      82 AT873 QJ865 5 \n            96 QJ964 AT32 AT \n\n",
    "15": "            AQ9 T972 - A96542\nT865 QJ5 Q9872 K      3 A63 KJ4 QJT873\n            KJ742 K84 AT653 -\nS\nW\n",
    "16": "            AK983 AQ75 Q42 6 \nT6542 4 J75 AKT8      Q7 KT96 K98 9432 \n            J J832 AT63 QJ75 \n\n",
    "17": "                         N ♠ A87 ♥ KJ54 ♦ A8753 ♣ 4\n W ♠ K52 ♥ A83 ♦ T ♣ AJ9653                      E ♠ Q964 ♥ QT2 ♦ KQJ942 ♣ -\n                         S ♠ JT3 ♥ 976 ♦ 6 ♣ KQT872\n",
    "18": "                         N ♠ Q972 ♥ KQ762 ♦ J4 ♣ J3\n W ♠ KT863 ♥ A ♦ K832 ♣ 962                      E ♠ - ♥ JT53 ♦ QT7 ♣ KQ8754\n                         S ♠ AJ54 ♥ 984 ♦ A965 ♣ AT\n",
    "19": "                         N ♠ AJ92 ♥ - ♦ KT864 ♣ KT53\n W ♠ KT76 ♥ AK983 ♦ 7 ♣ 987                      E ♠ Q854 ♥ JT64 ♦ J95 ♣ J6\n                         S ♠ 3 ♥ Q752 ♦ AQ32 ♣ AQ42\n",
    "2": "                Q73 2 A762 AJ973\nJ96 3 QJ95 K8642                K84 AJT754 8 QT5\n                AT52 KQ986 KT43 -\nS\nW\n",
    "3": "                 J94 AQ8 53 KQ873\nKQ85 J7 J96 AT65                 72 T652 AQ7 J942\n                 AT63 K943 KT842 -\n",
    "4": "                  - Q853 AJ962 KT74\nKT74 - Q853 AJ962                   Q853 AJ962 KT74 -\n                  AJ962 KT74 - Q853\nC\nW\n",
    "5": "             - A964 KJT76 K753\n Q8543 JT52 42 QT            AKT6 KQ87 3 A984\n             J972 3 AQ985 J62\n",
    "6": "            QT64 A754 8 J943\nKJ53 82 AT93 QT5      A872 KJ3 Q762 62\n            9 QT96 KJ54 AK87\nD\nS\n",
    "7": "            Q985 A74 82 A754 \nAJ63 QJT9 7643 9      KT74 8 AKJ5 QJ82 \n            2 K6532 QT9 KT63 \n\n",
    "8": "                         N ♠ 42 ♥ AQT63 ♦ K52 ♣ T84\n W ♠ KT8 ♥ KJ9875 ♦ Q8 ♣ 75                      E ♠ AJ65 ♥ 42 ♦ J963 ♣ KQJ\n                         S ♠ Q973 ♥ - ♦ AT74 ♣ A9632\n",
    "9": "                         N ♠ 3 ♥ JT83 ♦ AJ854 ♣ KT6\n W ♠ T ♥ AQ7 ♦ KT9763 ♣ 873                      E ♠ KJ875 ♥ K65 ♦ - ♣ AQ542\n                         S ♠ AQ9642 ♥ 942 ♦ Q2 ♣ J9\n"
  }
};
