#!/usr/bin/env python3
# Regenerates deals.js by embedding hard_deals/ and freak_deals/ deal text
# directly into the web app. GitHub Pages doesn't reliably serve symlinks
# (deployments can reject them outright), so the app can't rely on fetching
# ../hard_deals/deal.N at runtime -- baking the text into a JS file sidesteps
# that entirely, working the same on any static host.
import json
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
DEAL_FILE_RE = re.compile(r'^deal\.(\d+)$')


def load_dir(name):
    deals = {}
    for fname in os.listdir(os.path.join(ROOT, name)):
        match = DEAL_FILE_RE.match(fname)
        if not match:
            continue
        with open(os.path.join(ROOT, name, fname), encoding='utf-8') as f:
            deals[match.group(1)] = f.read()
    return deals


def main():
    data = {
        'hard_deals': load_dir('hard_deals'),
        'freak_deals': load_dir('freak_deals'),
    }
    with open(os.path.join(SCRIPT_DIR, 'deals.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by gen_deals.py -- do not edit by hand.\n')
        f.write('const DEALS = ')
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write(';\n')


if __name__ == '__main__':
    main()
